### ISSUE TITLE
Names are not up to date

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [alphartdev/BungeeAdminTools#10]
When doing a lookup, I can see the old name of the staff member who banned the player.

**Comment by alphartdev** [comment]
Once a player changed his name, he's to connect in order to update BAT cache

**Comment by TheOnlyRealTGS** [comment]
I was the player who banned that player

**Comment by alphartdev** [comment]
Oh yeah my bad. Staff member aren't UUID compatible.

**Comment by TheOnlyRealTGS** [comment]
Okay, I hope you add it!

**Comment by alphartdev** [comment]
It will ask a lot of refactorings so I don't think so. Sorry

**Comment by TheOnlyRealTGS** [comment]
Okay :(
