### ISSUE TITLE
BungeeAdminTools redis intergration

### ISSUE THREAD

**Issue by mechoriet** [alphartdev/BungeeAdminTools#16]
i have a question how well does your redis intergration work,
i have redis bungee
but dunno if its working or still buggy to use because you said in the config file its experimental 

and i want to know the state its working on 1.3.3

**Comment by alphartdev** [comment]
This notice should be removed, it was written when redis integration was just added but now it's pretty stable : RedisBungee supports work fine till 0.3.5. Latest version (0.3.6) has been known to cause some issues for some users.

**Comment by alphartdev** [comment]
Closed for now. Feel free to reopen if you have any other questions.
