### ISSUE TITLE
Wrong time value in /bat lookup

### ISSUE THREAD

**Issue by idkw** [alphartdev/BungeeAdminTools#22]
Hello

When I login and do :
`/bat lookup idkw`

I see :

![image](http://i.imgur.com/KSpn3gI.png)

I'm using the French translation.
In `Dernière connexion` which means  `Last login` the date is in the future, which doesn't make any sense.
It's written `demain à 00:59` which means `tomorrow at 00:59` 

When I look in the database, the date is correct at today 00:59. So it seems to be BAT fault.

My server is in the timezone UTC+2.00 if it can help

What could be the cause of that and how to solve it ?

**Comment by alphartdev** [comment]
Same issue is listed there, I can't fix it.
Une même erreur a déjà ouverte, je n'arrive pas à le reproduire de mon côté et du coup j'ai du mal à la réparer.
cf #19
