### ISSUE TITLE
{comments_number} 

### ISSUE THREAD

**Issue by Johandrex** [alphartdev/BungeeAdminTools#24]
I'd like the variable {comments_number} added to the lang file. Which should have the same functions as {bans_number} and {mutes_number} except that this should be showing the amount of comments/warnings.

**Comment by alphartdev** [comment]
Should not be too hard to do. I'll try to do it during december holidays. If you have no news before let's say the 20th, feel free to pm me.

**Comment by johandrex** [comment]
Awesome, thanks.

**Comment by Johandrex** [comment]
Fixed in the beta version
