### ISSUE TITLE
[Feature] Add in Event API

### ISSUE THREAD

**Issue by Samistine** [alphartdev/BungeeAdminTools#28]
I am developing an email plugin to send out mail when someone is banned, tempbanned, or kicked. 
If you don't want to do this, I can, but it might be ugly :tongue: 
I am asking for events such as BanEvent, Unban Event, and kick event.

System can be new UUID&currentname("00000000-00000000-00000000-00000000", "CONSOLE")

The ban Event:
- `Date getTime()` (_Current Time_)
- `UUID&currentname getVictim()` (_Player who's being banned_)
- `UUID&currentname getPerpetrator()` (_Player/System who's banning this player_)
- `String getBanMessage()`  (_The ban message_)
- `boolean isPermenant()` (_Is this a permanent ban, or a tempban?_)
- `Duration getBanLength()` (_Return the specified ban length, or null/infinity if permban_)
- `void cancel()` (_Prevent this ban from happening_)

The unban Event:
- `Date getTime()` (_Current Time_)
- `Date getBanTime()` (_Time of Ban_)
- `Duration getBannedLength()` (_The current time subtracted by the ban time_)
- `UUID&currentname getVictim()` (_The banned player_)
- `UUID&currentname getPerpetrator()` (_Player/System who banned this player originally_)
- `UUID&currentname getUnbanner()` (_Player/System who's attempting to unban this player_)
- `getBanMessage()` (_The original ban message_)
- `getUnbanMessage()` (_The currently supplied unban message_)
- `wasAutomatic()` (_Is this a scheduled unban of someone who is tempbanned_)
- `wasPermanent()` (_Is this a permanent Ban_)
- `Duration getBanLength()` (_How long is this ban for, originally_)
  Cancelling doesn't seem like a good idea, so if a plugin wants to keep the player banned they should just create a new ban.

Kick event:
- `Date getTime()` (_Current Time_)
- `UUID&currentname getVictim()`
- `UUID&currentname getPerpetrator()`
- `String getKickMessage()`
- void cancel()

**Comment by alphartdev** [comment]
Still looking for this?

**Comment by Samistine** [comment]
Yes, the funny thing is I was just thinking about this again today. I've
been waiting for a while, already got the email side done just need to be
able to hook in.

**Comment by Samistine** [comment]
Probably should use getCurrentTime instead of getTime as it would be less
confusing.

**Comment by James137137** [comment]
would something like this: http://pastebin.com/VkJL4dxX be acceptable

**Comment by Samistine** [comment]
@James137137 It's expired

**Comment by James137137** [comment]
yeah it would have... it was posted in march

**Comment by James137137** [comment]
https://gist.github.com/James137137/55749bd6addc79bf126bfbbe12de2d81

**Comment by James137137** [comment]
if you want to test out where i'm at so far here is my jenkins

http://jenkins.lolnet.co.nz/view/Other/job/BungeeAdminTools-Events-API/

**Comment by alphartdev** [comment]
Closing it for inactivity. Don't hesitate to ping either @James137137 or me if it's still relevant to you
