### ISSUE TITLE
Warn level  & Warn decay

### ISSUE THREAD

**Issue by Blacksheep92** [alphartdev/BungeeAdminTools#29]
Hey,
I have a suggestion for further functions.
### Warn Level

The function with the trigger is pretty nice.
As an an example, i've a trigger for 20 Points, to tempBan for 7 days.
Player XYZ is griefing some blocks -> warn
Player XYZ is griefing some blocks again -> warn
Player XYZ is griefing again & again ... -> So, at this point i will warn the player with 5 points, because he probably does not realize that he did something wrong. 

Actually, I should write 5 times "/warn XYZ Griefing"
But it would be nice to write "/warn XYZ Griefing 5"
(It would be nice to add a new column in the database with the points per warning, no point = 1)
### Warn decay

It would be cool to define a time period in which the trigger operates.
A Player is spamming & griefing in 2012, so he collected 17 warnings.
But he has learned from it.
2015, he make a mistake & gets 3 warnings, the trigger notice 20 & will execute.

It would be nice to define a count (20m, 1h, 7d, 2mo,...) where the trigger is counting the warns.
### Warn Position

Also, it would be very nice if a warning saves the server name, world, xyz coordinates.
To understand where and how he was warned.
(also a /warn tp for Staffmembers)

I know, this is a long list of features & needs some work on the database structure, but i think it will be worth it. (If you will work on this, u could also add this https://github.com/alphartdev/BAT-WebInterface/issues/7 ^^)

**Comment by alphartdev** [comment]
For the warn position, it won't be possible as BAT is only a Bungee plugin.

Concerning the warn level, I've to admit that it seems like a lot of troubles for nothing as we already have triggers. Furthermore if I understand your explanation properly, to add 'points' to a warn you would need to use the exact same reason and it's sometimes difficult to achieve such a coordination between the different members of a staff.

Finally for the warn decay, I might be interested in implementing trigger duration: like the period of time between the first warn and the current warn that might be causing the trigger to execute. If it's higher than something specified, then it's not taken into account.
