### ISSUE TITLE
From a bukkit server to bungeeadmintools

### ISSUE THREAD

**Issue by mechoriet** [alphartdev/BungeeAdminTools#35]
is there a way to send unban unmute command from a Spigot server(buycraft) to the bungee to execute commands for a user bought a unban for instance like thru a message channel or something.

**Comment by ItsJamesJ** [comment]
No. This is a BungeeCord plugin, you would have to use a separate plugin.

**Comment by alphartdev** [comment]
@ItsJamesJ is right! Gotta use ExecuteEverywhere or a related plugin
