### ISSUE TITLE
Add option to disable plugin (or parts of it) in certain server

### ISSUE THREAD

**Issue by Projekt4769** [alphartdev/BungeeAdminTools#36]
For example, if a player is globally muted, it would still be able to talk in server1, but not in other servers.

**Comment by alphartdev** [comment]
Well that's why there are local punishments?

**Comment by Projekt4769** [comment]
Local punishments work on "opt-in" principle, not "opt-out". What I had in mind was punishments on every server EXCEPT one server.

**Comment by alphartdev** [comment]
Oh ok.
Well no sorry it would ask to much refactoring for something that is already doable (but not practical at all, I grant you that)

**Comment by Projekt4769** [comment]
I'll have to work around it then, somehow. :D
