### ISSUE TITLE
Make /temban, /ban,/mute, /tempmute for multiples servers in one command (ip too)

### ISSUE THREAD

**Issue by zebigboss72** [alphartdev/BungeeAdminTools#41]
Hi !

I'm using BAT since a while, and i had a suggestion :
For the moment, it's not possible to ban/mute a player in 2 or 3 servers only, in one command. we have to run the command for each server where a player must be ban or mute.

I found 2 potentials solutions : 

1st idea : add multiples servers in a single command
 we could use /ban <player> <server1,server2,server3...> <reason>.  The problem is if the server names are too long, the ban reason will be too small.

2nd idea : create a named list of servers in a config file
in a config file, we can get a list of servers, like this : 

==============
list1:
    - server1
    - server2
    - server3
list2:
    - server2
    - server4
    - server5
    - server6
...

================

instead of running /ban <player> <server> <ban reason> for each server of the list, we can run something like this : /ban <player> <list> <ban reason>. With the config example i suggest, the command should be like this : /ban player555 list2 You just be banned :) . Player555 will be banned from servers 2 4 5 6. If he was already banned from server 2, the plugin doesn't ban hi a second time from this server (already an active feature in your plugin), but ban him from all other servers of list2. 

If i had to choose a solution, i think the second is better, because we can add longer messages as reasons.

here a list af all commands that can be impacted by my suggestions:
- /ban
- /tempban
- /banip
- /tempbanip
- /mute
- /muteip
- /tempmute
- /tempmuteip

If you need more details about my suggestion, ask me, i'm an active person.

**Comment by James137137** [comment]
Have you thought about making a plugin to handle this and hooking into the BAT API?

**Comment by zebigboss72** [comment]
i have currently no skills to make my own plugins. I can do a lots of thing for a server, (builds, configurations,skripts, permissions...), but i can't mak my plugins for the moment, because i had no knowledges in JAVA.
I have already ask my devs if they can make this change, until this feature 'll be added (or not) to the original plugin.

**Comment by alphartdev** [comment]
Well, I feel like most people who need to execute many commands and only want to type one are using alias command plugin and that's what I recommend you.

**Comment by alphartdev** [comment]
I might have a look into this but in the meantime I highly recommend you to use an alais plugin, which will always be more flexible (and work will all plugin).
