### ISSUE TITLE
SQLite to MySQL

### ISSUE THREAD

**Issue by Samistine** [alphartdev/BungeeAdminTools#48]
Could you add something to transition from sqlite to mysql?

**Comment by qlimax5000** [comment]
Isn't this already available? (https://github.com/alphartdev/BungeeAdminTools/blob/master/src/main/java/fr/Alphart/BAT/Modules/Core/Importer/SQLiteMigrater.java)

Or am I misunderstanding what you're looking for?

**Comment by alphartdev** [comment]
As qlimax pointed out it's already there since a long time
