### ISSUE TITLE
/gtempmute for seconds doesn't work 

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [alphartdev/BungeeAdminTools#5]
I did _/gtempmute Player 10s Don't dare speak for 10 sec_ and it never unmuted the player, and whenever he tried to talk he got the message "You were unmuted. Reason: No reason was specified"

**Comment by TheOnlyRealTGS** [comment]
This actually seesm to be an issue for all bans that last "seconds"

**Comment by alphartdev** [comment]
Hi,
yeah in fact 10s may cause a problem as it's exactly the duration between each update of the synchronization system. Could you try with a bigger duration such as 20s ? Thanks

**Comment by TheOnlyRealTGS** [comment]
Bigger amounts seem to work

**Comment by alphartdev** [comment]
Nice, so I may setup a limiter for duration < 20 sec, though I don't think many people are punishing for 10s.

**Comment by TheOnlyRealTGS** [comment]
Good idea
