### ISSUE TITLE
Problème de transfère, SQLite -> MySQL

### ISSUE THREAD

**Issue by Erdack54** [alphartdev/BungeeAdminTools#50]
Voilà l'erreur que j'ai quand je fais: /bat migrateToMysql sur mon serveur
03:21:54 [GRAVE] [BungeeAdminTools] An error has occured during the import of data from BATSQLite. Please report this :
03:21:54 [GRAVE] com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '3016-12-29 19:14:14.0' for column 'mute_end' at row 1
03:21:54 [GRAVE] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3885)
03:21:54 [GRAVE] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
03:21:54 [GRAVE] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
03:21:54 [GRAVE] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
03:21:54 [GRAVE] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530)
03:21:54 [GRAVE] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907)
03:21:54 [GRAVE] 	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1199)
03:21:54 [GRAVE] 	at com.zaxxer.hikari.proxy.PreparedStatementProxy.execute(PreparedStatementProxy.java:44)
03:21:54 [GRAVE] 	at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.execute(HikariPreparedStatementProxy.java)
03:21:54 [GRAVE] 	at fr.Alphart.BAT.Modules.Core.Importer.SQLiteMigrater.importData(SQLiteMigrater.java:106)
03:21:54 [GRAVE] 	at fr.Alphart.BAT.Modules.Core.Importer.Importer.startImport(Importer.java:47)
03:21:54 [GRAVE] 	at fr.Alphart.BAT.Modules.Core.CoreCommand$ImportCmd.onCommand(CoreCommand.java:469)
03:21:54 [GRAVE] 	at fr.Alphart.BAT.Modules.BATCommand$1.run(BATCommand.java:185)
03:21:54 [GRAVE] 	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
03:21:54 [GRAVE] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
03:21:54 [GRAVE] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
03:21:54 [GRAVE] 	at java.lang.Thread.run(Thread.java:745)

**Comment by Erdack54** [comment]
Problème régler, j'ai utiliser le programme "DB Browser for SQLite" et j'ai exporter toute les tables a format .csv que j'ai importer dans PHPMyAdmin et tout fonctionne, il faudrait quand même corriger ce bug du plugin, sinon le plugin et juste incroyable, sa fonctionne super bien donc GG !

**Comment by alphartdev** [comment]
Super merci de l'info pour "DB Browser for SQLite". Je transmettrais si le problème arrive de nouveau.
