### ISSUE TITLE
[Feature] Alternative users

### ISSUE THREAD

**Issue by KasperFranz** [alphartdev/BungeeAdminTools#51]
We would like it so we can see users with the same Ip history on the lookup command

**Comment by alphartdev** [comment]
Hi,
could you give more details please?

Currently here is what you get when you lookup an ip:

![](http://puu.sh/uyle9/12eb82ac4b.png)

So there is already a user list. Are you talking about something else?

**Comment by KasperFranz** [comment]
it was more on the user level so if you lookup an user you get that information

**Comment by alphartdev** [comment]
Alright so like you want the same list but automatically displayed on user lookup without having to run another command to lookup its ip?

**Comment by KasperFranz** [comment]
Yes exactly (sorry for the delay)

**Comment by alphartdev** [comment]
That has been added in the 1.5.2-premium, I'll tag you and close it's once it's released

**Comment by KasperFranz** [comment]
Do you have a Discord server where i can reach you, as we have some other things we would like in the plugin before we can fully switch to it (which is why I love open source, so I can change stuff etc :p)

**Comment by alphartdev** [comment]
Added you on discord.

**Comment by alphartdev** [comment]
1.5.2-premium has been implemented, see https://www.spigotmc.org/resources/bungee-admin-tools-premium-edition.37880/update?update=174832

The **{ip_users}** placeholder is what you're looking for.

Feel free to reopen if you need more informations.
