### ISSUE TITLE
[Feature] Silent flag

### ISSUE THREAD

**Issue by KasperFranz** [alphartdev/BungeeAdminTools#52]
Sometimes you want to ban a player without sending it to everyone on the network 

a example of a usecase can be /ban <player> [server] [reason] -S

**Comment by alphartdev** [comment]
Hi,
sorry for not responding to this request faster, I don't receive all notifications from Github (don't hesitate to PM me on spigot, if you have no answere here).

This feature is one of the new ones  in BAT premium which should be released this week.
Therefore I close that, feel free to reopen it if you have further questions.
