### ISSUE TITLE
Not saving in the BAT_players when banning a player

### ISSUE THREAD

**Issue by KasperFranz** [alphartdev/BungeeAdminTools#56]
If you are banning a player there hasn't been online before then it creates the entry in BAT_ban correctly but it doesn't add a entry to BAT_players which is making the web interface not work properly + the ban list will show the UUId instead

**Comment by alphartdev** [comment]
Online or offline mode?

**Comment by KasperFranz** [comment]
We are running online mode 
we know, it was some players prior to installing this plugin

**Comment by alphartdev** [comment]
The real reason for not adding player in the BAT_players is that I'm missing information (login date/logout date/ip) as the player was never on the server.
If users decide to ignore the warnings, it's their choice to do so and therefore assume the "consequences" so I'm not going to add code to fill the BAT_player table with "false information".

To go back to your issue, you wrote "we know, it was some players prior to installing this plugin", did you use an import module when migrating to BAT? If yes, you'll have to wait till player connects again for the same reason as above?

**Comment by KasperFranz** [comment]
Well, the case where this happened was that we banned a player who was on the server prior to BAT getting installed, and griefed, this player hasn't logged in after BAT was installed which is why the data wouldn't be available. 

I don't see it as false information, the firstLogin date and lastLogin date can always be false.

It is a rare case that something like this is happening I guess.

**Comment by alphartdev** [comment]
> I don't see it as false information, the firstLogin date and lastLogin date can always be false.
> It is a rare case that something like this is happening I guess.

I agree with you so I think I won't take extra care with this sort of race condition
