### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by Foorack** [alphartdev/BungeeAdminTools#58]
Please add support for MongoDB as database backend.

**Comment by alphartdev** [comment]
I would understand why you would go from NoSQL (eg Mongo) to SQL (eg MySQL), but I don't see why you'd like to do the opposite?

**Comment by Foorack** [comment]
@alphartdev I would understand why you would go from SQL to NoSQL, but I don't see why you support the opposite? :thinking:

Best would be if BAT had a generic database adapter and seamlessly supported multiple different types of backend storages. This would prevent users from being locked-in into a single database storage solution and give them more freedom on what they want to use.

**Comment by alphartdev** [comment]
On the other hand, SQL databases have much better perfomance in certain use case. For example, BAT use a lot indexes (almost all the queries) and I don't think that indexes of NoSQL database are as powerful as the ones of SQL databases for the use cases of BAT.
Don't hesitate to reopen if you have any other commentaries
