### ISSUE TITLE
Kick, then server crash

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [alphartdev/BungeeAdminTools#6]
A staff member kicked a player, then the bungee crashed, meaning noone could join, and ping didn't work, but most people were still on the servers.
Log:
17:58:44 [INFO] [BungeeAdminTools] §aNolreySan§e was §6kicked§e by §aTheTedfierro§e from the network. Reason : Spamming

**Comment by alphartdev** [comment]
Hi,
I have no clue what's causing that (nobody never met this issue before AFAIK).
Is it happening on a regular basis ?

**Comment by TheOnlyRealTGS** [comment]
No, but it was definitely caused by bat since the crash happened a second after

**Comment by alphartdev** [comment]
Ok, to be honest I can't really help on that problem. If it happens again, could you write down the message players are getting when they're trying to connect as well as the error message displayed in bungee log when they're trying to connect. Thanks !

**Comment by TheOnlyRealTGS** [comment]
I will thanks.
Den 02/02/2015 18.10 skrev "Alphart" <notifications@github.com>:
