### ISSUE TITLE
Translations not working properly with color codes.

### ISSUE THREAD

**Issue by iDarkfusion** [alphartdev/BungeeAdminTools#7]
First: Sorry for my eng, im spanish and my english its too bad.
Hi AlphartDev, i know you are absent.
I have a unknown bug, if i use multi-lines and color codes, the placeholder {0} on the translations, doesn't works (See the images)
![banerror1](https://cloud.githubusercontent.com/assets/5834569/5739950/ed3ce45c-9be5-11e4-89fe-4977932cf12b.png)

And the messages_en.language file:
(I know, colored messages in spanish on eng file)
![banerro2](https://cloud.githubusercontent.com/assets/5834569/5739960/0db3efa0-9be6-11e4-89d3-3626add8a161.png)

P.D: I think its a kick bug, if you see the first img, one kick with coloured msg, before the ban, and after the ban, a kick with [proxy] blah blah blah.. (Before the ban, i think bat doesn't replaces the placeholder, obviously.)

Thanks in advance.

**Comment by alphartdev** [comment]
I'm not sure what's causing that, though could you try to remove the backslash you put just before the {0} please ? And could also copy your wasBannedNotif line so I can do my test with the same setting than yours. Thanks

**Comment by alphartdev** [comment]
Closed for now, feel free to comment if you still meet this issue.
